import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Download, FileText, Copy, Check, Sparkles } from 'lucide-react'

function formatINR(v) {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency', currency: 'INR', maximumFractionDigits: 0,
  }).format(v || 0)
}

function InfoRow({ label, value }) {
  return (
    <div className="flex justify-between py-2 border-b border-white/5">
      <span className="text-white/45 text-xs">{label}</span>
      <span className="text-white/80 text-xs font-semibold">{value}</span>
    </div>
  )
}

export default function TripDoc({ tripData }) {
  const [copied,      setCopied]      = useState(false)
  const [generating,  setGenerating]  = useState(false)
  const [preview,     setPreview]     = useState(false)

  const dest    = tripData?.destination
  const details = tripData?.tripDetails || {}
  const budget  = tripData?.budget || {}
  const acts    = tripData?.activities || []

  if (!dest) return (
    <div className="text-center py-10">
      <div className="text-4xl mb-3">📄</div>
      <p className="text-white/40 text-sm">Complete your trip to generate summary</p>
    </div>
  )

  // ── Plain text ──
  const buildText = () => [
    '================================================',
    '         TRIPSMART - TRIP SUMMARY REPORT        ',
    '         Plan Smarter. Travel Better.           ',
    '================================================',
    '',
    'DESTINATION : ' + dest.name + ', ' + dest.country,
    'TAGLINE     : ' + (dest.tagline || ''),
    'START DATE  : ' + (details.startDate
      ? new Date(details.startDate).toLocaleDateString('en-IN',{
          weekday:'long', day:'numeric', month:'long', year:'numeric',
        })
      : 'Not set'),
    'DURATION    : ' + (details.duration || 0) + ' Nights',
    'TRAVELERS   : ' + (details.travelers || 0) + ' People',
    'TRIP TYPE   : ' + (details.tripType || 'N/A'),
    'STAY        : ' + (budget.accommodation || 'N/A').replace(/_/g,' '),
    'BEST TIME   : ' + (dest.best_time || ''),
    'CURRENCY    : ' + (dest.currency || ''),
    'LANGUAGE    : ' + (dest.language || ''),
    '',
    '------------------------------------------------',
    'BUDGET DETAILS',
    '------------------------------------------------',
    'Total Budget   : ' + formatINR(budget.total),
    'Per Person     : ' + formatINR(budget.perPerson),
    'Per Day        : ' + formatINR(budget.perDay),
    '',
    'Accommodation  : ' + formatINR(budget.breakdown?.stay)    + ' (35%)',
    'Food & Dining  : ' + formatINR(budget.breakdown?.food)    + ' (25%)',
    'Transport      : ' + formatINR(budget.breakdown?.transport)+ ' (20%)',
    'Activities     : ' + formatINR(budget.breakdown?.activities)+'(12%)',
    'Miscellaneous  : ' + formatINR(budget.breakdown?.misc)    + '  (8%)',
    '',
    '------------------------------------------------',
    'TOP ATTRACTIONS',
    '------------------------------------------------',
    ...(dest.attractions||[]).map((a,i) =>
      (i+1) + '. ' + a.name + ' | Rating: ' + a.rating + ' | ' + a.category
    ),
    '',
    '------------------------------------------------',
    'ACTIVITY PREFERENCES',
    '------------------------------------------------',
    ...acts.map(a => '- ' + a.charAt(0).toUpperCase() + a.slice(1)),
    '',
    '------------------------------------------------',
    'PACKING ESSENTIALS',
    '------------------------------------------------',
    ...(dest.packing||[]).map(p => '[  ] ' + p),
    '',
    '------------------------------------------------',
    'LOCAL FOOD TO TRY',
    '------------------------------------------------',
    ...(dest.food||[]).map(f => '* ' + f.name + ' (' + f.type + ') - ' + f.restaurant),
    '',
    '------------------------------------------------',
    'TRAVEL TIPS',
    '------------------------------------------------',
    '- Best time to visit : ' + dest.best_time,
    '- Currency           : ' + dest.currency,
    '- Local language     : ' + dest.language,
    '- Budget range       : ' + dest.avg_budget,
    '',
    '================================================',
    'Generated by TripSmart on ' + new Date().toLocaleDateString('en-IN'),
    'tripSmart - Plan Smarter. Travel Better.',
    '================================================',
  ].join('\n')

  // ── Download TXT ──
  const downloadTXT = () => {
    const blob = new Blob([buildText()], { type: 'text/plain;charset=utf-8' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = 'TripSmart_' + dest.name + '_Summary.txt'
    a.click()
    URL.revokeObjectURL(url)
  }

  // ── Download PDF ──
  const downloadPDF = async () => {
    setGenerating(true)
    try {
      const { jsPDF } = await import('jspdf')
      const doc  = new jsPDF('p','mm','a4')
      const pw   = doc.internal.pageSize.getWidth()
      const ph   = doc.internal.pageSize.getHeight()
      const mg   = 15
      let   cy   = mg

      const newPage = () => {
        doc.addPage()
        doc.setFillColor(8,6,24)
        doc.rect(0,0,pw,ph,'F')
        cy = mg
      }

      const chk = (h) => { if (cy + h > ph - mg) newPage() }

      const txt = (t, sz, bold, r,g,b, cx) => {
        doc.setFontSize(sz)
        doc.setFont('helvetica', bold ? 'bold' : 'normal')
        doc.setTextColor(r,g,b)
        const x = cx !== undefined ? cx : mg
        doc.text(String(t), x, cy)
        cy += sz * 0.42
      }

      const line = (r,g,b) => {
        doc.setDrawColor(r||100,g||80,b||200)
        doc.setLineWidth(0.25)
        doc.line(mg, cy, pw-mg, cy)
        cy += 4
      }

      const section = (title) => {
        chk(16)
        cy += 3
        doc.setFillColor(30,15,70)
        doc.roundedRect(mg-2, cy-5, pw-mg*2+4, 12, 2, 2, 'F')
        txt(title, 11, true, 167,139,250)
        cy += 2
      }

      // Background
      doc.setFillColor(8,6,24)
      doc.rect(0,0,pw,ph,'F')

      // Header box
      doc.setFillColor(20,10,60)
      doc.roundedRect(mg-5, cy-5, pw-mg*2+10, 38, 4, 4, 'F')
      doc.setDrawColor(124,58,237)
      doc.setLineWidth(0.5)
      doc.roundedRect(mg-5, cy-5, pw-mg*2+10, 38, 4, 4, 'S')

      cy += 4
      txt('TRIPSMART', 20, true, 167,139,250, pw/2 - 20)
      cy += 2
      txt('Plan Smarter. Travel Better.', 9, false, 148,163,184, pw/2 - 28)
      cy += 2
      txt('TRIP SUMMARY REPORT', 11, true, 96,165,250, pw/2 - 22)
      cy += 8

      line(124,58,237)

      // Overview
      section('TRIP OVERVIEW')
      const ov = [
        ['Destination', dest.name + ', ' + dest.country],
        ['Start Date',  details.startDate
          ? new Date(details.startDate).toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})
          : 'Not set'],
        ['Duration',    (details.duration||0) + ' Nights'],
        ['Travelers',   (details.travelers||0) + ' People'],
        ['Trip Type',   details.tripType || 'N/A'],
        ['Stay',        (budget.accommodation||'N/A').replace(/_/g,' ')],
        ['Best Time',   dest.best_time || ''],
        ['Currency',    dest.currency || ''],
        ['Language',    dest.language || ''],
      ]
      ov.forEach(([l,v]) => {
        chk(8)
        doc.setFontSize(9)
        doc.setFont('helvetica','bold')
        doc.setTextColor(148,163,184)
        doc.text(l + ':', mg+2, cy)
        doc.setFont('helvetica','normal')
        doc.setTextColor(220,220,220)
        doc.text(String(v), mg+42, cy)
        cy += 6.5
      })

      // Budget
      section('BUDGET DETAILS')
      const bd = [
        ['Total Budget',   formatINR(budget.total)],
        ['Per Person',     formatINR(budget.perPerson)],
        ['Per Day',        formatINR(budget.perDay)],
        ['Accommodation',  formatINR(budget.breakdown?.stay)   + ' (35%)'],
        ['Food & Dining',  formatINR(budget.breakdown?.food)   + ' (25%)'],
        ['Transport',      formatINR(budget.breakdown?.transport) + ' (20%)'],
        ['Activities',     formatINR(budget.breakdown?.activities)+ ' (12%)'],
        ['Misc',           formatINR(budget.breakdown?.misc)   + '  (8%)'],
      ]
      bd.forEach(([l,v]) => {
        chk(8)
        doc.setFontSize(9)
        doc.setFont('helvetica','bold')
        doc.setTextColor(148,163,184)
        doc.text(l + ':', mg+2, cy)
        doc.setFont('helvetica','normal')
        doc.setTextColor(52,211,153)
        doc.text(String(v), mg+42, cy)
        cy += 6.5
      })

      // Attractions
      section('TOP ATTRACTIONS')
      ;(dest.attractions||[]).forEach((a,i) => {
        chk(8)
        doc.setFontSize(9)
        doc.setFont('helvetica','bold')
        doc.setTextColor(220,220,220)
        doc.text((i+1) + '. ' + a.name, mg+2, cy)
        doc.setFont('helvetica','normal')
        doc.setTextColor(251,191,36)
        doc.text('  Rating: ' + a.rating, mg+80, cy)
        doc.setTextColor(148,163,184)
        doc.text('  ' + a.category, mg+110, cy)
        cy += 6.5
      })

      // Activities
      if (acts.length > 0) {
        section('ACTIVITY PREFERENCES')
        acts.forEach(a => {
          chk(8)
          doc.setFontSize(9)
          doc.setFont('helvetica','normal')
          doc.setTextColor(196,181,253)
          doc.text('- ' + a.charAt(0).toUpperCase() + a.slice(1), mg+4, cy)
          cy += 6.5
        })
      }

      // Packing
      if (dest.packing?.length) {
        section('PACKING ESSENTIALS')
        const half = Math.ceil(dest.packing.length / 2)
        dest.packing.forEach((p,i) => {
          chk(8)
          doc.setFontSize(9)
          doc.setFont('helvetica','normal')
          doc.setTextColor(220,220,220)
          const x = i < half ? mg+4 : pw/2 + 4
          if (i < half) {
            doc.text('[ ] ' + p, x, cy)
            cy += 6.5
          } else {
            doc.text('[ ] ' + p, x, cy - 6.5 * (i - half + 1) + 6.5 * (i - half))
          }
        })
      }

      // Food
      if (dest.food?.length) {
        section('LOCAL FOOD TO TRY')
        dest.food.forEach(f => {
          chk(10)
          doc.setFontSize(9)
          doc.setFont('helvetica','bold')
          doc.setTextColor(251,146,60)
          doc.text(f.name, mg+4, cy)
          doc.setFont('helvetica','normal')
          doc.setTextColor(148,163,184)
          doc.text('  ' + f.type + ' - ' + f.restaurant, mg+4, cy+5)
          cy += 12
        })
      }

      // Footer
      chk(20)
      cy += 5
      line(52,211,153)
      doc.setFontSize(8)
      doc.setFont('helvetica','normal')
      doc.setTextColor(100,116,139)
      doc.text(
        'Generated by TripSmart on ' + new Date().toLocaleDateString('en-IN'),
        pw/2, cy, { align: 'center' }
      )
      cy += 5
      doc.setTextColor(167,139,250)
      doc.setFont('helvetica','bold')
      doc.text('TripSmart - Plan Smarter. Travel Better.', pw/2, cy, { align:'center' })

      doc.save('TripSmart_' + dest.name + '_Summary.pdf')
    } catch (err) {
      console.error('PDF error:', err)
      downloadTXT()
    } finally {
      setGenerating(false)
    }
  }

  const copyText = async () => {
    try {
      await navigator.clipboard.writeText(buildText())
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    } catch { /* silent */ }
  }

  return (
    <div className="space-y-5">

      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl flex items-center justify-center text-xl"
            style={{ background:'linear-gradient(135deg,#f59e0b,#ea580c)' }}>
            📄
          </div>
          <div>
            <h2 className="text-xl font-bold text-white">Trip Summary</h2>
            <p className="text-white/40 text-xs">Download or share your complete trip plan</p>
          </div>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <motion.button whileTap={{ scale:0.95 }} onClick={copyText}
            className="flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-medium"
            style={{
              background:'rgba(255,255,255,0.06)',
              border:'1px solid rgba(255,255,255,0.1)',
              color: copied ? '#34d399' : 'rgba(255,255,255,0.6)',
            }}>
            {copied ? <Check size={13}/> : <Copy size={13}/>}
            {copied ? 'Copied!' : 'Copy'}
          </motion.button>

          <motion.button whileTap={{ scale:0.95 }} onClick={downloadTXT}
            className="flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-medium"
            style={{ background:'rgba(37,99,235,0.2)', border:'1px solid rgba(37,99,235,0.35)', color:'#93c5fd' }}>
            <FileText size={13}/> TXT
          </motion.button>

          <motion.button
            whileHover={{ scale:1.03, y:-1 }} whileTap={{ scale:0.97 }}
            onClick={downloadPDF} disabled={generating}
            className="btn-primary py-2 px-5 text-xs rounded-xl disabled:opacity-60"
          >
            {generating ? (
              <><motion.div animate={{ rotate:360 }} transition={{ duration:1, repeat:Infinity, ease:'linear' }}>
                <Sparkles size={13}/>
              </motion.div> Generating...</>
            ) : (
              <><Download size={13}/> Download PDF</>
            )}
          </motion.button>
        </div>
      </div>

      {/* Preview toggle */}
      <button onClick={() => setPreview(p => !p)}
        className="w-full flex items-center justify-between p-4 rounded-2xl transition-all"
        style={{ background:'rgba(255,255,255,0.03)', border:'1px solid rgba(255,255,255,0.07)' }}>
        <span className="text-white/55 text-sm flex items-center gap-2">
          <FileText size={14} className="text-violet-400"/>
          Preview Trip Summary
        </span>
        <span className="text-white/30 text-xs">{preview ? '▲ Hide' : '▼ Show'}</span>
      </button>

      <AnimatePresence>
        {preview && (
          <motion.div
            initial={{ opacity:0, height:0 }}
            animate={{ opacity:1, height:'auto' }}
            exit={{ opacity:0, height:0 }}
            className="overflow-hidden space-y-4"
          >
            {/* Overview */}
            <div className="rounded-2xl overflow-hidden"
              style={{ background:'rgba(124,58,237,0.08)', border:'1px solid rgba(124,58,237,0.2)' }}>
              <div className="px-4 py-2.5 text-white font-bold text-sm"
                style={{ background:'rgba(124,58,237,0.15)', borderBottom:'1px solid rgba(124,58,237,0.15)' }}>
                📍 Trip Overview
              </div>
              <div className="p-4 space-y-0.5">
                <InfoRow label="Destination"   value={dest.name + ', ' + dest.country} />
                <InfoRow label="Start Date"    value={details.startDate
                  ? new Date(details.startDate).toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})
                  : 'Not set'} />
                <InfoRow label="Duration"      value={(details.duration||0) + ' Nights'} />
                <InfoRow label="Travelers"     value={(details.travelers||0) + ' People'} />
                <InfoRow label="Trip Type"     value={details.tripType||'N/A'} />
                <InfoRow label="Accommodation" value={(budget.accommodation||'N/A').replace(/_/g,' ')} />
                <InfoRow label="Best Time"     value={dest.best_time||''} />
                <InfoRow label="Currency"      value={dest.currency||''} />
                <InfoRow label="Language"      value={dest.language||''} />
              </div>
            </div>

            {/* Budget */}
            <div className="rounded-2xl overflow-hidden"
              style={{ background:'rgba(245,158,11,0.07)', border:'1px solid rgba(245,158,11,0.2)' }}>
              <div className="px-4 py-2.5 text-white font-bold text-sm"
                style={{ background:'rgba(245,158,11,0.12)', borderBottom:'1px solid rgba(245,158,11,0.15)' }}>
                💰 Budget Details
              </div>
              <div className="p-4 space-y-0.5">
                <InfoRow label="Total Budget"   value={formatINR(budget.total)} />
                <InfoRow label="Per Person"     value={formatINR(budget.perPerson)} />
                <InfoRow label="Per Day"        value={formatINR(budget.perDay)} />
                <InfoRow label="Accommodation"  value={formatINR(budget.breakdown?.stay) + ' (35%)'} />
                <InfoRow label="Food & Dining"  value={formatINR(budget.breakdown?.food) + ' (25%)'} />
                <InfoRow label="Transport"      value={formatINR(budget.breakdown?.transport) + ' (20%)'} />
                <InfoRow label="Activities"     value={formatINR(budget.breakdown?.activities) + ' (12%)'} />
                <InfoRow label="Misc"           value={formatINR(budget.breakdown?.misc) + ' (8%)'} />
              </div>
            </div>

            {/* Attractions */}
            <div className="rounded-2xl overflow-hidden"
              style={{ background:'rgba(37,99,235,0.08)', border:'1px solid rgba(37,99,235,0.2)' }}>
              <div className="px-4 py-2.5 text-white font-bold text-sm"
                style={{ background:'rgba(37,99,235,0.12)', borderBottom:'1px solid rgba(37,99,235,0.15)' }}>
                🏛️ Top Attractions
              </div>
              <div className="p-4 grid grid-cols-1 sm:grid-cols-2 gap-2">
                {(dest.attractions||[]).map((a,i) => (
                  <div key={a.name} className="flex items-center gap-2 p-2 rounded-xl"
                    style={{ background:'rgba(255,255,255,0.03)' }}>
                    <span className="w-6 h-6 rounded-lg flex items-center justify-center text-xs font-bold text-white flex-shrink-0"
                      style={{ background:'linear-gradient(135deg,#7c3aed,#2563eb)' }}>
                      {i+1}
                    </span>
                    <div className="min-w-0">
                      <div className="text-white/80 text-xs font-semibold truncate">{a.name}</div>
                      <div className="text-amber-400 text-xs">⭐ {a.rating} · {a.category}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Packing */}
            {dest.packing?.length > 0 && (
              <div className="rounded-2xl overflow-hidden"
                style={{ background:'rgba(16,185,129,0.07)', border:'1px solid rgba(16,185,129,0.2)' }}>
                <div className="px-4 py-2.5 text-white font-bold text-sm"
                  style={{ background:'rgba(16,185,129,0.12)', borderBottom:'1px solid rgba(16,185,129,0.15)' }}>
                  🎒 Packing Essentials
                </div>
                <div className="p-4 grid grid-cols-2 sm:grid-cols-3 gap-2">
                  {dest.packing.map(p => (
                    <div key={p} className="flex items-center gap-2 text-xs text-white/65">
                      <Check size={11} className="text-emerald-400 flex-shrink-0"/> {p}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Footer */}
            <div className="text-center p-4 rounded-2xl"
              style={{ background:'rgba(124,58,237,0.07)', border:'1px solid rgba(124,58,237,0.15)' }}>
              <div className="text-2xl mb-2">🌍</div>
              <p className="text-violet-300 font-bold text-sm">TripSmart</p>
              <p className="text-white/30 text-xs mt-1">Plan Smarter. Travel Better.</p>
              <p className="text-white/20 text-xs mt-1">
                Generated on {new Date().toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}