import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  Download, FileText, Share2, Copy,
  Check, Printer, MapPin, Calendar,
  Users, Moon, Wallet, Star,
  Sparkles, Package, CheckSquare
} from 'lucide-react'

function formatINR(value) {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(value || 0)
}

function SummarySection({ title, emoji, children, color }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-2xl overflow-hidden"
      style={{
        background: 'rgba(255,255,255,0.03)',
        border: '1px solid rgba(255,255,255,0.07)',
      }}
    >
      <div
        className="px-5 py-3 flex items-center gap-2"
        style={{
          background: color || 'rgba(124,58,237,0.1)',
          borderBottom: '1px solid rgba(255,255,255,0.06)',
        }}
      >
        <span className="text-lg">{emoji}</span>
        <span className="text-white font-bold text-sm">{title}</span>
      </div>
      <div className="p-5">{children}</div>
    </motion.div>
  )
}

function InfoRow({ label, value, highlight }) {
  return (
    <div className="flex items-center justify-between py-2"
      style={{ borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
      <span className="text-white/45 text-xs font-medium">{label}</span>
      <span className={`text-xs font-semibold ${highlight ? 'text-violet-300' : 'text-white/80'}`}>
        {value}
      </span>
    </div>
  )
}

export default function TripSummary({ tripData }) {
  const [copied,       setCopied]       = useState(false)
  const [downloading,  setDownloading]  = useState(false)
  const [showPreview,  setShowPreview]  = useState(false)

  const destination  = tripData?.destination
  const tripDetails  = tripData?.tripDetails || {}
  const budget       = tripData?.budget || {}
  const activities   = tripData?.activities || []

  if (!destination) {
    return (
      <div className="text-center py-12">
        <div className="text-4xl mb-3">📄</div>
        <p className="text-white/40 text-sm">Complete your trip to generate summary</p>
      </div>
    )
  }

  // ── Build plain text summary ──
  const buildTextSummary = () => {
    const line = '─'.repeat(50)
    const lines = [
      '🌍 TRIPSMART – TRIP SUMMARY',
      'Plan Smarter. Travel Better.',
      line,
      '',
      `📍 DESTINATION: ${destination.name}, ${destination.country}`,
      `📅 START DATE:  ${tripDetails.startDate
        ? new Date(tripDetails.startDate).toLocaleDateString('en-IN', {
            weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
          })
        : 'Not set'}`,
      `🌙 DURATION:    ${tripDetails.duration || 0} Nights`,
      `👥 TRAVELERS:   ${tripDetails.travelers || 0} People`,
      `✈️  TRIP TYPE:   ${tripDetails.tripType || 'N/A'}`,
      `🏨 STAY:        ${(budget.accommodation || 'N/A').replace(/_/g, ' ')}`,
      '',
      line,
      '💰 BUDGET DETAILS',
      line,
      `Total Budget:  ${formatINR(budget.total)}`,
      `Per Person:    ${formatINR(budget.perPerson)}`,
      `Per Day:       ${formatINR(budget.perDay)}`,
      '',
      'Budget Breakdown:',
      `  • Accommodation: ${formatINR(budget.breakdown?.stay)}  (35%)`,
      `  • Food & Dining: ${formatINR(budget.breakdown?.food)}  (25%)`,
      `  • Transport:     ${formatINR(budget.breakdown?.transport)}  (20%)`,
      `  • Activities:    ${formatINR(budget.breakdown?.activities)}  (12%)`,
      `  • Miscellaneous: ${formatINR(budget.breakdown?.misc)}  (8%)`,
      '',
      line,
      '🎯 ACTIVITY PREFERENCES',
      line,
      activities.map(a => `  • ${a.charAt(0).toUpperCase() + a.slice(1)}`).join('\n'),
      '',
      line,
      '📍 TOP ATTRACTIONS',
      line,
      ...(destination.attractions || []).map(
        (a, i) => `  ${i + 1}. ${a.name} — ⭐ ${a.rating} (${a.category})`
      ),
      '',
      line,
      '🎒 PACKING ESSENTIALS',
      line,
      ...(destination.packing || []).map(p => `  ✓ ${p}`),
      '',
      line,
      '🍜 LOCAL FOOD TO TRY',
      line,
      ...(destination.food || []).map(
        f => `  • ${f.name} — ${f.type} @ ${f.restaurant}`
      ),
      '',
      line,
      '💡 QUICK TRAVEL TIPS',
      line,
      `  • Best Time to Visit: ${destination.best_time}`,
      `  • Currency: ${destination.currency}`,
      `  • Language: ${destination.language}`,
      `  • Avg Budget Range: ${destination.avg_budget}`,
      '',
      line,
      `Generated by TripSmart on ${new Date().toLocaleDateString('en-IN')}`,
      'tripSmart.app — Plan Smarter. Travel Better.',
      line,
    ]
    return lines.join('\n')
  }

  // ── Download as TXT ──
  const downloadTXT = () => {
    setDownloading(true)
    setTimeout(() => {
      const text = buildTextSummary()
      const blob = new Blob([text], { type: 'text/plain' })
      const url  = URL.createObjectURL(blob)
      const a    = document.createElement('a')
      a.href     = url
      a.download = `TripSmart_${destination.name}_Summary.txt`
      a.click()
      URL.revokeObjectURL(url)
      setDownloading(false)
    }, 800)
  }

  // ── Download as PDF using jsPDF ──
  const downloadPDF = async () => {
    setDownloading(true)
    try {
      const { jsPDF } = await import('jspdf')
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

      const pageW  = doc.internal.pageSize.getWidth()
      const pageH  = doc.internal.pageSize.getHeight()
      const margin = 20
      let   y      = margin

      const addText = (text, size, bold, color, align, xPos) => {
        doc.setFontSize(size)
        doc.setFont('helvetica', bold ? 'bold' : 'normal')
        doc.setTextColor(...(color || [255, 255, 255]))
        const x = align === 'center' ? pageW / 2 : xPos || margin
        doc.text(text, x, y, align === 'center' ? { align: 'center' } : {})
        y += size * 0.45
      }

      const addLine = (colorArr) => {
        doc.setDrawColor(...(colorArr || [124, 58, 237]))
        doc.setLineWidth(0.3)
        doc.line(margin, y, pageW - margin, y)
        y += 5
      }

      const checkPage = (needed) => {
        if (y + needed > pageH - margin) {
          doc.addPage()
          // Re-draw dark bg on new page
          doc.setFillColor(8, 6, 24)
          doc.rect(0, 0, pageW, pageH, 'F')
          y = margin
        }
      }

      // ── Background ──
      doc.setFillColor(8, 6, 24)
      doc.rect(0, 0, pageW, pageH, 'F')

      // ── Header band ──
      doc.setFillColor(30, 10, 80)
      doc.roundedRect(margin - 5, y - 5, pageW - (margin * 2) + 10, 45, 4, 4, 'F')

      addText('🌍 TripSmart', 22, true, [167, 139, 250], 'center')
      y += 3
      addText('Plan Smarter. Travel Better.', 10, false, [148, 163, 184], 'center')
      y += 3
      addText(`Trip Summary — ${destination.name}`, 13, true, [96, 165, 250], 'center')
      y += 10

      addLine([124, 58, 237])

      // ── Destination Info ──
      checkPage(60)
      addText('📍 TRIP OVERVIEW', 13, true, [167, 139, 250])
      y += 3

      const overviewData = [
        ['Destination',  `${destination.name}, ${destination.country}`],
        ['Tagline',      destination.tagline || ''],
        ['Start Date',   tripDetails.startDate
          ? new Date(tripDetails.startDate).toLocaleDateString('en-IN', {
              day: 'numeric', month: 'long', year: 'numeric',
            })
          : 'Not set'],
        ['Duration',     `${tripDetails.duration || 0} Nights`],
        ['Travelers',    `${tripDetails.travelers || 0} People`],
        ['Trip Type',    tripDetails.tripType || 'N/A'],
        ['Accommodation',(budget.accommodation || 'N/A').replace(/_/g, ' ')],
        ['Best Time',    destination.best_time || ''],
        ['Currency',     destination.currency || ''],
        ['Language',     destination.language || ''],
      ]

      overviewData.forEach(([label, value]) => {
        checkPage(10)
        doc.setFontSize(10)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(148, 163, 184)
        doc.text(label + ':', margin, y)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(255, 255, 255)
        doc.text(String(value), margin + 45, y)
        y += 7
      })

      y += 5
      addLine()

      // ── Budget ──
      checkPage(70)
      addText('💰 BUDGET DETAILS', 13, true, [167, 139, 250])
      y += 3

      const budgetData = [
        ['Total Budget',   formatINR(budget.total)],
        ['Per Person',     formatINR(budget.perPerson)],
        ['Per Day',        formatINR(budget.perDay)],
        ['Accommodation',  `${formatINR(budget.breakdown?.stay)} (35%)`],
        ['Food & Dining',  `${formatINR(budget.breakdown?.food)} (25%)`],
        ['Transport',      `${formatINR(budget.breakdown?.transport)} (20%)`],
        ['Activities',     `${formatINR(budget.breakdown?.activities)} (12%)`],
        ['Miscellaneous',  `${formatINR(budget.breakdown?.misc)} (8%)`],
      ]

      budgetData.forEach(([label, value]) => {
        checkPage(10)
        doc.setFontSize(10)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(148, 163, 184)
        doc.text(label + ':', margin, y)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(52, 211, 153)
        doc.text(String(value), margin + 45, y)
        y += 7
      })

      y += 5
      addLine()

      // ── Attractions ──
      checkPage(20)
      addText('📍 TOP ATTRACTIONS', 13, true, [167, 139, 250])
      y += 3

      ;(destination.attractions || []).forEach((a, i) => {
        checkPage(10)
        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(255, 255, 255)
        doc.text(`${i + 1}. ${a.name}`, margin, y)
        doc.setTextColor(251, 191, 36)
        doc.text(`⭐ ${a.rating}`, margin + 100, y)
        doc.setTextColor(148, 163, 184)
        doc.text(`${a.category}`, margin + 130, y)
        y += 7
      })

      y += 5
      addLine()

      // ── Activities ──
      checkPage(20)
      addText('🎯 ACTIVITY PREFERENCES', 13, true, [167, 139, 250])
      y += 3

      activities.forEach(a => {
        checkPage(8)
        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(196, 181, 253)
        doc.text(`• ${a.charAt(0).toUpperCase() + a.slice(1)}`, margin + 4, y)
        y += 7
      })

      y += 5
      addLine()

      // ── Packing ──
      checkPage(20)
      addText('🎒 PACKING ESSENTIALS', 13, true, [167, 139, 250])
      y += 3

      ;(destination.packing || []).forEach(p => {
        checkPage(8)
        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(255, 255, 255)
        doc.text(`✓ ${p}`, margin + 4, y)
        y += 7
      })

      y += 5
      addLine()

      // ── Food ──
      checkPage(20)
      addText('🍜 LOCAL FOOD TO TRY', 13, true, [167, 139, 250])
      y += 3

      ;(destination.food || []).slice(0, 4).forEach(f => {
        checkPage(10)
        doc.setFontSize(10)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(255, 255, 255)
        doc.text(`• ${f.name}`, margin + 4, y)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(148, 163, 184)
        doc.text(` — ${f.type} @ ${f.restaurant}`, margin + 30, y)
        y += 7
      })

      y += 8
      addLine([52, 211, 153])

      // ── Footer ──
      checkPage(20)
      addText(
        `Generated by TripSmart on ${new Date().toLocaleDateString('en-IN')}`,
        9, false, [100, 116, 139], 'center'
      )
      y += 3
      addText('Plan Smarter. Travel Better. — TripSmart', 9, true, [167, 139, 250], 'center')

      // Save
      doc.save(`TripSmart_${destination.name}_Summary.pdf`)
    } catch (err) {
      console.error('PDF error:', err)
      // Fallback to TXT
      downloadTXT()
    } finally {
      setDownloading(false)
    }
  }

  // ── Copy to clipboard ──
  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(buildTextSummary())
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    } catch {
      setCopied(false)
    }
  }

  return (
    <div className="space-y-6">

      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div className="flex items-center gap-3">
          <div
            className="w-10 h-10 rounded-xl flex items-center justify-center text-xl"
            style={{ background: 'linear-gradient(135deg, #f59e0b, #ea580c)' }}
          >
            📄
          </div>
          <div>
            <h2 className="text-xl font-bold text-white">Trip Summary</h2>
            <p className="text-white/40 text-xs">
              Download or share your complete trip plan
            </p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-2 flex-wrap">
          <motion.button
            whileTap={{ scale: 0.95 }}
            onClick={copyToClipboard}
            className="flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-medium transition-all"
            style={{
              background: 'rgba(255,255,255,0.06)',
              border: '1px solid rgba(255,255,255,0.1)',
              color: copied ? '#34d399' : 'rgba(255,255,255,0.6)',
            }}
          >
            {copied ? <Check size={13} /> : <Copy size={13} />}
            {copied ? 'Copied!' : 'Copy Text'}
          </motion.button>

          <motion.button
            whileTap={{ scale: 0.95 }}
            onClick={downloadTXT}
            className="flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-medium transition-all"
            style={{
              background: 'rgba(37,99,235,0.2)',
              border: '1px solid rgba(37,99,235,0.35)',
              color: '#93c5fd',
            }}
          >
            <FileText size={13} />
            Download TXT
          </motion.button>

          <motion.button
            whileHover={{ scale: 1.03, y: -1 }}
            whileTap={{ scale: 0.97 }}
            onClick={downloadPDF}
            disabled={downloading}
            className="btn-primary flex items-center gap-2 py-2 px-5 text-xs rounded-xl disabled:opacity-60"
          >
            {downloading ? (
              <>
                <motion.div
                  animate={{ rotate: 360 }}
                  transition={{ duration: 1, repeat: Infinity, ease: 'linear' }}
                >
                  <Sparkles size={13} />
                </motion.div>
                Generating...
              </>
            ) : (
              <>
                <Download size={13} />
                Download PDF
              </>
            )}
          </motion.button>
        </div>
      </div>

      {/* Toggle Preview */}
      <motion.button
        onClick={() => setShowPreview(p => !p)}
        className="w-full flex items-center justify-between p-4 rounded-2xl transition-all"
        style={{
          background: 'rgba(255,255,255,0.03)',
          border: '1px solid rgba(255,255,255,0.07)',
        }}
      >
        <span className="text-white/60 text-sm font-medium flex items-center gap-2">
          <FileText size={15} className="text-violet-400" />
          Preview Trip Summary
        </span>
        {showPreview
          ? <span className="text-white/30 text-xs">▲ Hide</span>
          : <span className="text-white/30 text-xs">▼ Show</span>}
      </motion.button>

      {/* Preview Content */}
      <AnimatePresence>
        {showPreview && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            className="overflow-hidden space-y-4"
          >

            {/* Trip Overview */}
            <SummarySection
              title="Trip Overview"
              emoji="📍"
              color="rgba(124,58,237,0.15)"
            >
              <InfoRow label="Destination"  value={`${destination.name}, ${destination.country}`} highlight />
              <InfoRow label="Tagline"      value={destination.tagline || '—'} />
              <InfoRow
                label="Start Date"
                value={tripDetails.startDate
                  ? new Date(tripDetails.startDate).toLocaleDateString('en-IN', {
                      weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
                    })
                  : 'Not set'}
              />
              <InfoRow label="Duration"     value={`${tripDetails.duration || 0} Nights`} />
              <InfoRow label="Travelers"    value={`${tripDetails.travelers || 0} People`} />
              <InfoRow label="Trip Type"    value={tripDetails.tripType || 'N/A'} highlight />
              <InfoRow
                label="Accommodation"
                value={(budget.accommodation || 'N/A').replace(/_/g, ' ')}
              />
              <InfoRow label="Best Time"    value={destination.best_time || '—'} />
              <InfoRow label="Currency"     value={destination.currency || '—'} />
              <InfoRow label="Language"     value={destination.language || '—'} />
            </SummarySection>

            {/* Budget */}
            <SummarySection
              title="Budget Details"
              emoji="💰"
              color="rgba(245,158,11,0.12)"
            >
              <InfoRow label="Total Budget"   value={formatINR(budget.total)} highlight />
              <InfoRow label="Per Person"     value={formatINR(budget.perPerson)} />
              <InfoRow label="Per Day"        value={formatINR(budget.perDay)} />
              <div className="mt-3 space-y-2">
                {[
                  { label: 'Accommodation', pct: 35, amount: budget.breakdown?.stay,       color: '#a78bfa' },
                  { label: 'Food & Dining', pct: 25, amount: budget.breakdown?.food,       color: '#fb923c' },
                  { label: 'Transport',     pct: 20, amount: budget.breakdown?.transport,  color: '#60a5fa' },
                  { label: 'Activities',    pct: 12, amount: budget.breakdown?.activities, color: '#34d399' },
                  { label: 'Misc',          pct: 8,  amount: budget.breakdown?.misc,       color: '#f472b6' },
                ].map(item => (
                  <div key={item.label} className="space-y-1">
                    <div className="flex justify-between text-xs">
                      <span className="text-white/45">{item.label} ({item.pct}%)</span>
                      <span style={{ color: item.color }} className="font-semibold">
                        {formatINR(item.amount)}
                      </span>
                    </div>
                    <div className="h-1.5 rounded-full overflow-hidden"
                      style={{ background: 'rgba(255,255,255,0.06)' }}>
                      <motion.div
                        className="h-full rounded-full"
                        style={{ background: item.color }}
                        initial={{ width: 0 }}
                        animate={{ width: `${item.pct}%` }}
                        transition={{ duration: 0.8 }}
                      />
                    </div>
                  </div>
                ))}
              </div>
            </SummarySection>

            {/* Attractions */}
            <SummarySection
              title="Top Attractions"
              emoji="📍"
              color="rgba(37,99,235,0.12)"
            >
              <div className="space-y-2">
                {(destination.attractions || []).map((a, i) => (
                  <div
                    key={a.name}
                    className="flex items-center justify-between p-2 rounded-xl"
                    style={{ background: 'rgba(255,255,255,0.03)' }}
                  >
                    <div className="flex items-center gap-2">
                      <span
                        className="w-6 h-6 rounded-lg flex items-center justify-center text-xs font-bold text-white"
                        style={{ background: 'linear-gradient(135deg,#7c3aed,#2563eb)' }}
                      >
                        {i + 1}
                      </span>
                      <span className="text-white/75 text-xs font-medium">{a.name}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="text-amber-400 text-xs">⭐ {a.rating}</span>
                      <span
                        className="text-xs px-2 py-0.5 rounded-full"
                        style={{
                          background: 'rgba(124,58,237,0.2)',
                          color: 'rgba(196,181,253,0.8)',
                        }}
                      >
                        {a.category}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </SummarySection>

            {/* Activities */}
            {activities.length > 0 && (
              <SummarySection
                title="Activity Preferences"
                emoji="🎯"
                color="rgba(16,185,129,0.1)"
              >
                <div className="flex flex-wrap gap-2">
                  {activities.map(a => (
                    <span
                      key={a}
                      className="px-3 py-1.5 rounded-full text-xs font-medium capitalize"
                      style={{
                        background: 'rgba(124,58,237,0.2)',
                        border: '1px solid rgba(124,58,237,0.3)',
                        color: 'rgba(196,181,253,0.9)',
                      }}
                    >
                      {a}
                    </span>
                  ))}
                </div>
              </SummarySection>
            )}

            {/* Packing */}
            {destination.packing?.length > 0 && (
              <SummarySection
                title="Packing Essentials"
                emoji="🎒"
                color="rgba(251,191,36,0.1)"
              >
                <div className="grid grid-cols-2 gap-2">
                  {destination.packing.map(p => (
                    <div key={p} className="flex items-center gap-2 text-xs text-white/65">
                      <Check size={11} className="text-emerald-400 flex-shrink-0" />
                      {p}
                    </div>
                  ))}
                </div>
              </SummarySection>
            )}

            {/* Food */}
            {destination.food?.length > 0 && (
              <SummarySection
                title="Local Food to Try"
                emoji="🍜"
                color="rgba(249,115,22,0.1)"
              >
                <div className="space-y-2">
                  {destination.food.map(f => (
                    <div
                      key={f.name}
                      className="flex items-center gap-3 p-2 rounded-xl"
                      style={{ background: 'rgba(255,255,255,0.03)' }}
                    >
                      <span className="text-2xl">{f.emoji}</span>
                      <div>
                        <div className="text-white/80 text-xs font-semibold">{f.name}</div>
                        <div className="text-white/35 text-xs">{f.type} · {f.restaurant}</div>
                      </div>
                    </div>
                  ))}
                </div>
              </SummarySection>
            )}

            {/* Footer */}
            <div
              className="text-center p-4 rounded-2xl"
              style={{
                background: 'rgba(124,58,237,0.08)',
                border: '1px solid rgba(124,58,237,0.15)',
              }}
            >
              <div className="text-2xl mb-2">🌍</div>
              <p className="text-violet-300 font-bold text-sm">TripSmart</p>
              <p className="text-white/30 text-xs mt-1">Plan Smarter. Travel Better.</p>
              <p className="text-white/20 text-xs mt-1">
                Generated on {new Date().toLocaleDateString('en-IN', {
                  day: 'numeric', month: 'long', year: 'numeric',
                })}
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}